---
title: "Wine Data"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(ggrepel)
knitr::opts_chunk$set(echo = TRUE)
```

```{r load}

## CellarTracker
f1 <- "./data/cellartracker_with_ids.csv"
df_ct <- read_csv(f1)
#df_ct %>% knitr::kable()
f2 <- "./data/cellartracker_facts.csv"
df_ctf <- read_csv(f2)
#df_ctf %>% knitr::kable()

# Global Wine Score
f3 <- "./data/globalwinescore_with_ids.csv"
df_gw <- read_csv(f3)
#df_gw %>% knitr::kable()
f4 <- "./data/globalwinescore_facts.csv"
df_gwf <- read_csv(f4)
#df_gwf %>% knitr::kable()

# Wine Reviews 94+
f5 <- "./data/winereviews94p_with_ids.csv"
df_wr <- read_csv(f5)
#df_wr %>% knitr::kable()
f6 <- "./data/winereviews94p_facts.csv"
df_wrf <- read_csv(f6)
#df_wrf %>% knitr::kable()
```
```{r load2}
# Wine Reviews
f7 <- "./data/winereviews.csv"
df_winereviews <- read_csv(f7)
#df_winereviews %>% knitr::kable()
```

```{r join_facts}
  df_cellartracker_facts <- df_ct %>%
  inner_join(
    df_ctf,
    by = c("_id", "_vintageId")
  ) %>%
  filter(`_id` != 'NA')

  df_globalwinescore_facts <- df_gw %>%
  inner_join(
    df_gwf,
    by = c("_id", "_vintageId")
  ) %>%
  filter(`_id` != 'NA')
  
  df_winereviews_facts <- df_wr %>%
  inner_join(
    df_wrf,
    by = c("_id", "_vintageId")
  ) %>%
  filter(`_id` != 'NA')

  glimpse(df_cellartracker_facts)
  glimpse(df_globalwinescore_facts)
  glimpse(df_winereviews_facts)
```

```{r vintages}
df_winereviews <-
df_winereviews %>%
  mutate(
    vintage = parse_number(title)
  ) %>%
  filter(vintage > 1900 & vintage < 2020) %>%
  glimpse
```
  

```{r sideways}

df_baseline <- df_winereviews %>%
              filter(vintage > 2000 & vintage < 2015)

df_sideways <- df_baseline %>%
  filter(variety == 'Merlot' | variety == 'Pinot Noir') %>%
  filter(province %in% c('California', 'Burgundy', 'Bordeaux'))

# Reviews of Merlot/Pinot over Vintage
df_sideways %>%
  ggplot(aes(x = vintage, y = points)) +
  geom_smooth(aes(color = variety)) +
  geom_smooth(data = df_baseline, color = "black") +
  geom_vline(xintercept = 2004) +
  labs(title = "Reviews of Merlot & Pinot Noir before & after 'Sideways'",
       color = "Varietal")

# Price of Merlot/Pinot over Vintage
df_sideways %>%
  ggplot(aes(x = vintage, y = price)) +
  geom_smooth(aes(color = variety)) +
  geom_smooth(data = df_baseline, color = "black") +
  geom_vline(xintercept = 2004) +
  labs(title = "Prices of Merlot & Pinot Noir before & after 'Sideways'",
       color = "Varietal")

# Reviews of Merlot/Pinot over Region
df_sideways %>%
  ggplot(aes(x = vintage, y = points)) +
  geom_smooth(aes(color = province)) +
  geom_smooth(data = df_baseline, color = "black") +
  geom_vline(xintercept = 2004) +
  labs(title = "Reviews of Merlot & Pinot Noir From Premium Regions",
       color = "Region")

```

```{r goodYearsFR}

df_years <- df_winereviews %>%
    filter(vintage >= 1999 & vintage <= 2015)

df_france <- df_years %>%
  filter(country == 'France')

# Provinces
df_years %>%
  filter(province %in% c('Burgundy',
                         'Bordeaux',
                         'Alsace',
                         'Rhône Valley',
                         'Beaujolais',
                         'Loire Valley',
                         'Languedoc-Roussillon',
                         'Champagne',
                         'Provence'
                         )) %>%
  ggplot(aes(x = vintage, y = points, color = province)) +
  geom_smooth(se = FALSE) +
  geom_smooth(data = df_france, color = 'black', se = FALSE) +
  labs(title = "Reviews of Vintages in French Winegrowing Regions",
       color = "Region")

# Burgundy Grand Crus
df_years %>%
  filter(region_1 %in% c('Gevrey-Chambertin',
                         'Morey-Saint-Denis',
                         'Chambolle-Musigny',
                         'Flagey-Echézeaux',
                         'Vosne-Romanée'
                         )) %>%
  ggplot(aes(x = vintage, y = price, color = region_1)) +
  geom_smooth(se = FALSE) +
  geom_vline(xintercept = 2002, color = 'green') +
  geom_vline(xintercept = 2015, color = 'green') +
  
  geom_vline(xintercept = 2008, color = 'red') +

  geom_smooth(data = df_france, color = 'black', se = FALSE) +
  labs(title = "Prices of Vintages in Premium Burgundy Sub-Regions",
       color = "Sub-Region")

# Bordeaux First Growths
df_years %>%
  filter(region_1 %in% c('Pessac-Léognan',
                         'Pauillac',
                         'Margaux'
                         )) %>%
  ggplot(aes(x = vintage, y = price, color = region_1)) +
  geom_smooth() +
  geom_smooth(data = df_france, color = 'black', se = FALSE) +
  
  geom_vline(xintercept = 2009, color = 'green') +
  geom_vline(xintercept = 2002, color = 'red') +

  labs(title = "Prices of Vintages in Premium Bordeaux Sub-Regions",
    color = "Sub-Region")

# Northern Rhone
df_years %>%
  filter(region_1 %in% c('Condrieu',
                         'Saint-Joseph',
                         'Crozes-Hermitage',
                         'Hermitage',
                         'Cornas',
                         'Châteauneuf-du-Pape'
                         )) %>%
  ggplot(aes(x = vintage, y = points, color = region_1)) +
  geom_smooth(se = FALSE) +
  geom_smooth(data = df_france, color = 'black', se = FALSE) +
  labs(title = "Reviews of Vintages in Premium Rhône Valley Sub-Regions",
    color = "Sub-Region")

```

```{r goodYearsUS}

df_years <- df_winereviews %>%
    filter(vintage >= 1999 & vintage <= 2015)

df_us <- df_years %>%
  filter(country == 'US')

df_ca <- df_years %>%
  filter(province == 'California')

# States
df_years %>%
    filter(province %in% c('California',
                           'Washington',
                           'New York'
                         )) %>%
  ggplot(aes(x = vintage, y = points, color = province)) +
  geom_smooth(se = FALSE) +
  labs(title = "Reviews of Vintages in Winegrowing US States",
    color = "State")

# California
df_years %>%
  filter(province == 'California') %>%
  ggplot(aes(x = vintage, y = points, color = region_2)) +
  geom_smooth(se = FALSE) +
  geom_smooth(data = df_us, color = 'black', se = FALSE) +
  labs(title = "Reviews of Vintages in California Winegrowing Regions",
    color = "Region")

# Napa
df_years %>%
  filter(region_2 == 'Napa') %>%
  filter(region_1 %in% c(
    'Calistoga',
    'Diamond Mountain District',
    'Spring Mountain District',
    'Mount Veeder',
    'St. Helena',
    'Rutherford',
    'Oakville',
    'Yountville',
    'Stags Leap District',
    'Oak Knoll',
    'Coombsville',
    'Wild Horse Valley',
    'Atlas Peak',
    'Chiles Valley District',
    'Howell Mountain',
    'Los Carneros'
  )) %>%
  ggplot(aes(x = vintage, y = points, color = region_1)) +
  geom_smooth(se = FALSE) +
  geom_smooth(data = df_ca, color = 'black', se = FALSE) + 
  labs(title = "Reviews of Vintages in Napa Valley AVA Sub-Regions",
    color = "Sub-Region")

# Sonoma
df_years %>%
  filter(region_2 == 'Sonoma') %>%
  filter(region_1 %in% c(
    'Russian River Valley',
    'Sonoma Valley',
    'Dry Creek Valley'
  )) %>%
  ggplot(aes(x = vintage, y = points, color = region_1)) +
  geom_smooth(se = FALSE) +
  geom_smooth(data = df_ca, color = 'black', se = FALSE) + 
  labs(title = "Reviews of Vintages in Sonoma AVA Sub-Regions",
    color = "Sub-Region")
```

```{r helpers}
Mode <- function(x) {
  ux <- unique(x)
  ux[which.max(tabulate(match(x, ux)))]
}
```

```{r pro_vs_amateur}
df_compreview <-
  df_winereviews_facts %>%
  summarize(
    price = price.x,
    pro = points / 20.0,
    amateur = rating
  )

df_compreview %>%
  ggplot(aes(x = price)) +
  geom_smooth(aes(y = pro), color = 'red') +
  geom_smooth(aes(y = amateur), color = 'blue') + 
  labs(title = "User Reviews vs. Professional Reviews",
       y = 'Rating (Adjusted)')
```

```{r varietal}

df_varietal <-
  df_winereviews_facts %>%
  group_by(variety) %>%
  summarize(
    ### aroma/flavor notes
    tannin = ordered(tannin, levels = c("low", "medium (-)", "medium", "medium (+)", "high"))
    #sweetness = Mode(sweetness),
    #acidity = Mode(acidity),
    #tannin = Mode(tannin),
    #alcohol = Mode(alcohol),

    #intensity = Mode(flavorIntensity),
  ) %>%
  glimpse

df_varietal %>%
  filter(variety %in% c('Gamay', 'Pinot Noir', 'Cabernet Sauvignon')) %>%
  ggplot(aes(x = variety)) +
  geom_boxplot(aes(y = tannin))
```

```{r joinDatasets}
  df_allwines_facts <- df_cellartracker_facts %>%
  left_join(
    df_globalwinescore_facts,
    by = c("_id", "_vintageId")
  ) %>%
  left_join(
    df_winereview_facts,
    by = c("_id", "_vintageId")
  )

glimpse(df_allwines_facts)
```

```{r vintages_facts}
df_allwines_facts %>%
  ggplot() +
  geom_point(
    aes(x = vintage.x, y = GWS)
  ) +
  facet_wrap(~region.x)

```

```{r styles}
df_allwines_facts %>%
  ggplot() +
  geom_point(
            aes(x = price.x.x, y = GWS)
            ) +
  facet_wrap(~style)
```